In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('customer_shopping_behavior_synthetic.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Backpack,Accessories,33,Nebraska,M,Orange,Fall,3.8,No,Next Day Air,Yes,Yes,31,Bank Transfer,Quarterly
1,2,28,Female,Boots,Footwear,23,New Mexico,M,Beige,Winter,4.5,Yes,Free Shipping,Yes,Yes,18,PayPal,Weekly
2,3,23,Female,Scarf,Accessories,92,New York,S,Magenta,Summer,4.6,No,Standard,No,No,18,Cash,Weekly
3,4,43,Male,Hat,Accessories,28,Louisiana,M,Gold,Spring,2.6,Yes,Free Shipping,Yes,Yes,33,Credit Card,Fortnightly
4,5,49,Male,Pants,Clothing,31,Arkansas,L,Yellow,Spring,2.7,No,2-Day Shipping,No,No,50,Bank Transfer,Quarterly

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [4]:
df.describe()

,Customer ID,Age,Purchase Amount (USD),Review Rating,Previous Purchases
count,3900.000000,3900.000000,3900.000000,3863.000000,3900.000000
mean,1950.500000,44.300000,58.913333,3.754595,25.372821
std,1125.977353,15.202042,23.380023,0.719978,14.553101
min,1.000000,18.000000,20.000000,2.500000,1.000000
25%,975.750000,31.000000,38.000000,3.100000,13.000000
50%,1950.500000,45.000000,58.000000,3.700000,25.500000
75%,2925.250000,57.000000,79.000000,4.400000,38.000000
max,3900.000000,70.000000,100.000000,5.000000,50.000000

In [5]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Coat,Clothing,NaN,Virginia,M,Green,Summer,NaN,No,2-Day Shipping,No,No,NaN,Cash,Annually
freq,NaN,NaN,2643,184,1766,NaN,94,1724,179,1044,NaN,2844,682,2187,2187,NaN,693,642
mean,1950.500000,44.300000,NaN,NaN,NaN,58.913333,NaN,NaN,NaN,NaN,3.754595,NaN,NaN,NaN,NaN,25.372821,NaN,NaN
std,1125.977353,15.202042,NaN,NaN,NaN,23.380023,NaN,NaN,NaN,NaN,0.719978,NaN,NaN,NaN,NaN,14.553101,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,38.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,45.000000,NaN,NaN,NaN,58.000000,NaN,NaN,NaN,NaN,3.700000,NaN,NaN,NaN,NaN,25.500000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,79.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [6]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [7]:
df['Review Rating']=df.groupby(by='Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [8]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [9]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ', '_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [10]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [11]:
df['age'].value_counts().sort_index()

age
18    80
19    64
20    65
21    65
22    66
23    68
24    66
25    79
26    85
27    60
28    59
29    89
30    91
31    71
32    72
33    84
34    75
35    68
36    60
37    76
38    56
39    63
40    83
41    77
42    63
43    66
44    87
45    70
46    76
47    82
48    65
49    81
50    95
51    94
52    69
53    74
54    91
55    77
56    81
57    60
58    61
59    82
60    69
61    68
62    67
63    58
64    77
65    84
66    64
67    84
68    80
69    82
70    71
Name: count, dtype: int64

In [12]:
labels=['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group']=pd.qcut(df['age'], 4, labels=labels)

In [13]:
df[['age', 'age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   28  Young Adult
2   23  Young Adult
3   43        Adult
4   49  Middle-aged
5   34        Adult
6   22  Young Adult
7   53  Middle-aged
8   35        Adult
9   59       Senior

In [14]:
df['frequency_of_purchases'].value_counts()

frequency_of_purchases
Annually          642
Every 3 Months    580
Monthly           558
Fortnightly       539
Quarterly         538
Weekly            530
Bi-Weekly         513
Name: count, dtype: int64

In [15]:
freq_mapping={'Annually':365, 'Every 3 Months':90,
             'Monthly':30, 'Fortnightly':14,
             'Quarterly':90, 'Weekly':7,
             'Bi-Weekly':14}
df['purchase_freq_days']=df['frequency_of_purchases'].map(freq_mapping)

In [16]:
df[['frequency_of_purchases', 'purchase_freq_days']].head(10)

  frequency_of_purchases  purchase_freq_days
0              Quarterly                  90
1                 Weekly                   7
2                 Weekly                   7
3            Fortnightly                  14
4              Quarterly                  90
5              Bi-Weekly                  14
6         Every 3 Months                  90
7            Fortnightly                  14
8              Quarterly                  90
9         Every 3 Months                  90

In [17]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2               No              No
3              Yes             Yes
4               No              No
5               No              No
6              Yes             Yes
7               No              No
8              Yes             Yes
9               No              No

In [18]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [19]:
df=df.drop('promo_code_used', axis=1)
df.head(10)

,customer_id,age,gender,item_purchased,category,purchase_amount,location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,previous_purchases,payment_method,frequency_of_purchases,age_group,purchase_freq_days
0,1,55,Male,Backpack,Accessories,33,Nebraska,M,Orange,Fall,3.8,No,Next Day Air,Yes,31,Bank Transfer,Quarterly,Middle-aged,90
1,2,28,Female,Boots,Footwear,23,New Mexico,M,Beige,Winter,4.5,Yes,Free Shipping,Yes,18,PayPal,Weekly,Young Adult,7
2,3,23,Female,Scarf,Accessories,92,New York,S,Magenta,Summer,4.6,No,Standard,No,18,Cash,Weekly,Young Adult,7
3,4,43,Male,Hat,Accessories,28,Louisiana,M,Gold,Spring,2.6,Yes,Free Shipping,Yes,33,Credit Card,Fortnightly,Adult,14
4,5,49,Male,Pants,Clothing,31,Arkansas,L,Yellow,Spring,2.7,No,2-Day Shipping,No,50,Bank Transfer,Quarterly,Middle-aged,90
5,6,34,Female,Gloves,Accessories,74,Arizona,L,Beige,Fall,4.1,No,Free Shipping,No,36,Venmo,Bi-Weekly,Adult,14
6,7,22,Male,Coat,Outerwear,61,Illinois,S,Red,Fall,3.0,No,Free Shipping,Yes,33,Credit Card,Every 3 Months,Young Adult,90
7,8,53,Female,Handbag,Accessories,43,Idaho,L,Black,Winter,4.8,No,Store Pickup,No,3,Debit Card,Fortnightly,Middle-aged,14
8,9,35,Female,Backpack,Accessories,23,South Dakota,L,Turquoise,Fall,3.4,Yes,Store Pickup,Yes,41,Bank Transfer,Quarterly,Adult,90
9,10,59,Male,Shoes,Footwear,40,California,S,Gray,Summer,4.0,Yes,Express,No,42,Cash,Every 3 Months,Senior,90

In [20]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (2.9.13)
Requirement already satisfied: sqlalchemy in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\admin\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: C:\Users\ADMIN\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip

In [21]:
from sqlalchemy import create_engine

username='postgres'
password='root'
host='localhost'
port='5432'
database='CustomerBehavior'

engine=create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name='customerpurchases'
df.to_sql(table_name, engine, if_exists='replace', index=False)

print(f"Data loaded into table '{table_name}' in database '{database}'")

Data loaded into table 'customerpurchases' in database 'CustomerBehavior'

In [22]:
df.shape

(3900, 19)